#!/bin/expect

set username [lindex $argv 0]
set ip1 [lindex $argv 1]
set ip2 [lindex $argv 2]
set pass [lindex $argv 3]

set timeout 100

spawn ssh -o StrictHostKeyChecking=no ec2-user@$ip1
      expect "ec2-user@" {send "logout\r"}

spawn ssh  -o StrictHostKeyChecking=no -J ec2-user@$ip1 ec2-user@$ip2

expect "ec2-user@" {
  send "sudo yum install -y mariadb mariadb-server\r"
  send "sudo systemctl start mariadb\r"
  send " mysql_secure_installation\r"
}

        expect ":" {
          send " \n"
          }
            expect "n]" {send "y\r"}
            expect ":" {
              send "$pass\n"
              send "$pass\n"
              }
            expect "n]" {send "y\r y\r y\r y\r"}

expect "ec2-user@" {
  send " systemctl enable mariadb\r"
  send " wget https://downloads.mysql.com/docs/sakila-db.tar.gz\r"
  send " tar -xf sakila-db.tar.gz\r"
  send " mysql -u root -p\r"}
    expect "Enter password: " {send "$pass\r"}
        expect "none)]> " {
          send "source sakila-db/sakila-schema.sql\r"
          send "source sakila-db/sakila-data.sql\r"
            send "show full tables;\r";
}

interact
